### ISSUE TITLE
用語集の用語をレビューする

### ISSUE THREAD

**Issue by yosshy** [openstack-ja/openstack-manuals#10]
校正作業に先立って、用語集の用語部分をレビューする。

**Comment by yosshy** [comment]
#opst12 でレビューしました。

決まったこと：
- 「ー」は -er, -or 等の単語で付け、-y, -a 等の単語では付けない事としました。
- 半角文字と全角文字の間は半角空白を１つ入れる事にしました。
  - 但し「レイヤ2」だけは空白を入れない事としました。
- 複数語をカタカナベースで訳す場合に中黒（・）は付けない事にしました。

決まらなかったこと：
- keystone, glance 等の固有名詞について頭文字を大文字にするかどうか。
- 用語集の説明の文体を「ですます」調にするか「だである」調にするか。
- 「weighing」の訳し方。

**Comment by ghost** [comment]
用語集の説明は「だである」調にしましょうか。

**Comment by ghost** [comment]
ドキュメント全体のレビューとして実施済み。
