### ISSUE TITLE
Cloud Nightmareの一部の文章の翻訳リソースが存在しない

### ISSUE THREAD

**Issue by takekawa** [openstack-ja/openstack-manuals#35]
「ダブルVLAN」の二つの注記が翻訳されていません。
http://dream.daynight.jp/openstack/openstack-ops/content/double_vlan.html
リソース漏れのようです。追加と翻訳をおねがいできますでしょうか?

**Comment by amotoki** [comment]
きちんとした手順を取ろうとすると、Transifex にアップロードされているものを（翻訳元言語も含めて）更新する必要があります。
お手軽な方法としては、openstack-ja repo で管理している ja.po のみを更新する方法があります。
とりあえず、他の作業を先に進めましょうか？

**Comment by ghost** [comment]
Transifexを確認したところ、翻訳されているようです。
翻訳対象文に「&lt;placeholder-1&gt;」が含まれているため、poをマージした際にパターンマッチに失敗するようです。
原文「&lt;command&gt;ps aux&lt;/command&gt;」がなぜ「&lt;placeholder-1/&gt;」に変換されているのか確認してから、
別途、報告したほうがよさそうですね。
（翻訳してはいけないコマンドをわざわざ除外しているように見えます。）

お手軽な方法として、ドキュメントを生成するときに、取り込んだ最新poファイルを適当に文字列変換しようかと思います。
同じ注記が2つ並んでいるようなので、一つは捨てたいと思います。

**Comment by ghost** [comment]
原因がわかりました。
DocBookソースに翻訳を反映するツールの考慮漏れでした。
私のほうからアップストリームに報告しておきます。

翻訳用のpotファイルの生成時にコマンドなどを翻訳対象から除外（placeholderに置き換え）していますが、DocBookに翻訳を反映するツールにおいて、同様の処理がなされていないため、
翻訳原文の不一致になり翻訳が反映されていませんでした。

**Comment by ghost** [comment]
ツールの問題、注釈が重複している問題について、対応されました。
https://github.com/openstack/operations-guide/commit/b47d0fb6335fc91e018a27f4cdae867169e0d459
https://github.com/openstack/operations-guide/commit/e77fba0fd139f7e013edf5c1719e0fa10397be98
