### ISSUE TITLE
Pythonのサンプルコードのインデントが消えている

### ISSUE THREAD

**Issue by takekawa** [openstack-ja/openstack-manuals#36]
http://dream.daynight.jp/openstack/openstack-ops/content/customize.html
で確認しましたがpythonコードのサンプルでインデントが死んでしまっているので、そのままでは利用できないコードになっています。

**Comment by amotoki** [comment]
原文の方もそうなっていますね。 upstream で修正方法を議論すべきと思います。
ops-guide 翻訳での議論対象からは外して、本家のバグとしましょう。

**Comment by amotoki** [comment]
https://bugs.launchpad.net/openstack-manuals/+bug/1203622

**Comment by amotoki** [comment]
調査したところ、オリジナルの XML ですでにインデントが付いていませんでした。
修正パッチを Gerrit に投稿中です。

**Comment by amotoki** [comment]
Merged into the master of ops-guide: https://review.openstack.org/#/c/38281/
