### ISSUE TITLE
用語: service catalog vs サービスカタログ

### ISSUE THREAD

**Issue by amotoki** [openstack-ja/openstack-manuals#37]
service catalog と サービスカタログが混在している。
他の用語ではカタカナのものが多いので、サービスカタログが妥当なところか。

https://github.com/openstack-ja/openstack-manuals/commit/bc99a034c276dc6d740aed155714df77441e8684#doc-src-docbkx-openstack-ops-locale-chap-ch_ops_lay_of_land-xml-ja-po-P426

**Comment by ghost** [comment]
固有名詞ではないので「サービスカタログ」に賛成です。

**Comment by amotoki** [comment]
「サービスカタログ」に統一しましょう。
表記揺れの確認をしてからクローズしたいと思います。
