### ISSUE TITLE
用語: Image Service, Image API などの訳し方

### ISSUE THREAD

**Issue by amotoki** [openstack-ja/openstack-manuals#38]
OpenStack Image Service, Image Service, Image API などの固有名詞があるが、
訳の方では、Image、イメージのように分かれている。

Identity Service, Compute Service, Volume Service なども同様。

opst12 の議論を見る限りでは、Image API, Identity API を使う方向。

**Comment by amotoki** [comment]
個人的には、訳さないもの (Image|Identity|Compute|Volume) (Service|API) がよいと思っています。固有名詞なので。

**Comment by ghost** [comment]
固有名詞は訳さない方針に決まったかと思います。
今更恥ずかしい質問ですが、Image Service までが固有名詞でしょうか？
(Image|Identity|Compute|Volume) (サービス|API) かな、と思っていました。

**Comment by amotoki** [comment]
私もよく分かりません。 www.openstack.org の各サービスの説明によると、
glance と keystone は OpenStack Image Service と OpenStack Identity Service になっています。
それ以外はOpenStack Compute/Networking/Object Storage/Block Storage のように、固有名詞に Service は含まれていませんでした。

Service も含めて固有名詞にした方がいいかなと思った理由は、原文で Compute Service のように両方とも大文字になっている場合が多かったという理由もあります。他の理由としては、Service がつくものとつかないものがあるので、統一してしまった方が分かりやすいかなと思ったというのがあります。

他の皆さんはいかがでしょうか？

**Comment by yosshy** [comment]
https://wiki.openstack.org/wiki/Programs が正確な名称一覧と思います。

**Comment by amotoki** [comment]
古すぎるのでクローズする

**Comment by amotoki** [comment]
古すぎるのでクローズする
