### ISSUE TITLE
用語： flavor の訳は？ フレーバー、インスタンスタイプ、インスタンス種別

### ISSUE THREAD

**Issue by amotoki** [openstack-ja/openstack-manuals#41]
flavor の訳として、フレーバー、インスタンスタイプ、インスタンス種別、が混在している。

Horizon の翻訳では、フレーバーではなく、インスタンスタイプ(or 種別) が使われている。
一方、opst12 の議論ではフレーバーを使う方向になっている。

個人的には「フレーバー」に一票です。

**Comment by ghost** [comment]
私は「フレーバー」のほうが好きです。
Horizonの訳語を作るときに、「インスタンスタイプ」に決めたようなのですが、そのときの経緯などわかる方はいないでしょうか。
