### ISSUE TITLE
crash consistent の意味

### ISSUE THREAD

**Issue by amotoki** [openstack-ja/openstack-manuals#42]
crash consistent って何でしょうか？ よく分かりませんでした。

https://github.com/openstack-ja/openstack-manuals/pull/34/files#r4834339

**Comment by amotoki** [comment]
ch_ops_user_facing.xml.ja.po L.692 付近の話です。

+"Remember this is a block level snapshot which is crash consistent so it is "
+"best if the volume is not connected to an instance when the snapshot is "
+"taken and second best if the volume is not in use on the instance it is "

**Comment by yosshy** [comment]
http://www.datasaver-pro.com/datasaver/06.html に説明がありました。
書き込み可能でオープンされたファイルを綺麗にバックアップ出来ない事を指すようです。

**Comment by amotoki** [comment]
この辺りの記事が理解の助けになるようですね。
http://www.altaro.com/hyper-v/vss-crash-consistent-vs-application-consistent-vss-backups-post-1-of-2/

だいたい理解はできるのですが、何かいい訳はないかなというのが悩みです。

今の訳の「クラッシュに対する一貫性があります」でも意味が分かることは分かりますがどうでしょうか？

**Comment by amotoki** [comment]
現在はこのように訳しています。
https://github.com/openstack-ja/operations-guide/blob/ja-20130726/doc/src/docbkx/openstack-ops/locale/ja.po#L17310

**Comment by amotoki** [comment]
いつまでも放置しておいても意味がないので、いったんクローズします。
