### ISSUE TITLE
全体・変更履歴・用語集 (bk_ops_guide.xml)の校正用ページにソースが表示されない

### ISSUE THREAD

**Issue by torumakabe** [openstack-ja/openstack-manuals#43]
https://github.com/openstack-ja/openstack-manuals/pull/14/files

ソースが表示されないのですが、みなさんいかがでしょうか?

**Comment by amotoki** [comment]
私も表示されません。長すぎるからかもしれません。ちょっと試してみます。

**Comment by amotoki** [comment]
4つのファイルに分割してみました。 part1 から part4 までに分かれています。やはり長すぎるのが原因だったようです。
https://github.com/openstack-ja/openstack-manuals/pull/14/files では、
ファイル単位のジャンプがありませんが、part1 から part4 で検索してジャンプしてみて下さい。

**Comment by torumakabe** [comment]
ありがとうございますっ

**Comment by ghost** [comment]
ありがとうございます。作業を進められるようになりました。
