### ISSUE TITLE
コロンと句読点の使い方

### ISSUE THREAD

**Issue by ghost** [openstack-ja/openstack-manuals#46]
To install xx, run:
    pip install

のような形で、コロンで続ける場合があります。
コロンを残している場合と句読点に変更している場合が混在しています。
どちらかに統一しませんか。
私はコロンのまま残すことが好きですが、句読点に変更して、より日本語的にされている方が多いようです。

**Comment by amotoki** [comment]
難しいところですね。句読点に一票入れておきます。
別の翻訳でも同様の議論があります。日本語はコロンを使う文化自体が元々ないので、句読点に変更することが多いです。

**Comment by ghost** [comment]
個別項目のレビューの中で、句読点に変更してきているので、なるべくコロン（：）を句読点に変更しましょう。
