### ISSUE TITLE
While OpenStack is composed of many components and moving parts, 

### ISSUE THREAD

**Issue by amotoki** [openstack-ja/openstack-manuals#50]
目立つようにしておきたいので、Issue にも登録します。
https://github.com/openstack-ja/openstack-manuals/pull/24

バックアップ対象について議論しているところで、以下の様な表現があり、
moving parts はどのように訳すのがいいだろう？というはなしです。

While OpenStack is composed of many components and moving parts, backing up 
the critical data is quite simple.

**Comment by yosshy** [comment]
moving parts は「動く部分」「可動部分」という意味があるようですが、バックアップ関連の文脈では変更しうる下記のファイル群（/var/lib/ 配下にある仮想ディスクのバックエンドファイル、ボリュームのバックエンドストレージ、データベースファイル等）あるいはそれらを変更するプログラムの意味だと思います。

**Comment by amotoki** [comment]
docs ML で質問しています。

**Comment by amotoki** [comment]
以下のような返事をもらいました。

> Moving parts -> dynamic or changing
> (However, I don't think that's relevant to the sentence.)
> 
> "While OpenStack has many components, backing up critical data is quite simple."
> 
> You could also say
> While OpenStack is a dynamic platform with many components, backing up critical data is quite simple.

---

> "Moving parts" comes from the notion of machinery, such as an engine. The parts that move are the ones that are most likely to fail (or be involved in a failure) so they need the most attention.
> 
> In this context, it means that OpenStack has a lot of pieces that are vulnerable and need to be looked after.

**Comment by amotoki** [comment]
この場合、「面倒をみないといけない箇所がたくさんある」といった感じですね。

**Comment by amotoki** [comment]
https://github.com/openstack-ja/openstack-manuals/pull/24 でのコメントも有用なので、こちらにも再掲しておきます。

(irixjp)
While OpenStack is composed of many components and moving parts
「OpenStackには多くのコンポーネントと可動部が含まれているが」のほうがしっくりくる感じですねかね。

(amotoki)
「可動部」としてもまだ何のことかよく分からないです。元の moving parts の意味自体がよく分かっていません。
コンピュータシステムで moving parts という表現は個人的には初めて見ました。
「動的に変化する部分、要素」といった感じでしょうか。 ご意見求む！

(yosshy)
moving parts は機械的な可動部分の事で、パソコンで言えば HDD や冷却ファン、キーボード、LCDのヒンジ等です。
バックアップの章の文脈では、OpenStack ソフトウェア以外の関連ソフトウェア（DB、AMQP、memcached、ハイパーバイザ、他）を指しているのではないでしょうか。
ぶっちゃけ、原文を書いた人間に聞くのが一番です。

(katomo)
OpenStackのコンポーネントそのもの以外の可変部分、つまりパッケージから復元できない部分かなと思います。
次の文に出てくる設定ファイルやデータベース（の中身）、他にはログファイルなども含まれるのかなと思いました。
私も原文を書いた人に聞くほうがいいと思います。
少し曖昧な表現なので、表現方法を変更するか、いくつか例示してもらえるよう、改善要望を出してみるといかがでしょうか。

**Comment by amotoki** [comment]
最新版では以下のようにしてみました。 https://github.com/openstack-ja/openstack-manuals/commit/751c42c92fcf9795412a1939d98f8e8088270158

「OpenStack は多くのコンポーネントから構成され、注意を払うべき箇所もたくさんありますが、大事なデータのバックアップは非常に単純です。」
