### ISSUE TITLE
質問：トレンドレポートについて

### ISSUE THREAD

**Issue by ghost** [openstack-ja/openstack-manuals#51]
ちょっとした質問をさせてください。
以下のページ [1] において、ログを定期的に確認してトレンドレポートを作成していますが、行数だけ確認すればよくないでしょうか。
wc コマンドで行数は出力されますが、wc -l としたほうが不要な情報が出力されず、良いのではないでしょうか。

 [1] http://openstack-ja.github.io/openstack-manuals/openstack-ops/content/logging_monitoring.html#trending

リクエストの概数を取得するには/var/log/nova/nova-api.logのINFOメッセージを検索します。

 # grep INFO /var/log/nova/nova-api.log | wc

成功したリクエストを検索することで、更なる情報を取得できます。

 # grep " 200 " /var/log/nova/nova-api.log | wc

このコマンドを定期的に実行し結果を記録することで、トレンドレポートを作ることができます。

**Comment by amotoki** [comment]
ここでは、イベント数を数えているだけなので、ログであれば行数が確認できればよく、wc -l で十分ですね。

**Comment by ghost** [comment]
ありがとうございます。そうですよね。
原文にフィードバックしてみてもいいかもしれませんね。
