### ISSUE TITLE
原文: コンポーネントの固有名詞の定義があいまい

### ISSUE THREAD

**Issue by amotoki** [openstack-ja/openstack-manuals#53]
原文で、OpenStackコンポーネントの表記がかなり揺れている。

Glance : OpenStack Image Service と Image Catalog and Delivery Service
Neutron : OpenStack Network Service

など。

他にもあれば追加して下さい。

**Comment by yosshy** [comment]
Block Storage service $B$H$+HyL/$JI=8=$,$"$j$^$9!#(B
$B0lJ}!"(BCompute service $B$O$J$+$C$?$h$&$K;W$$$^$9!#(B
2013/07/14 1:18 "Akihiro MOTOKI" notifications@github.com:

**Comment by amotoki** [comment]
メールでリプライしたためか、文字化けしています。
もう一度送ってもらえませんか。

**Comment by yosshy** [comment]
Block Storage service とか微妙な表現があります。
一方、Compute service はなかったように思います。

**Comment by amotoki** [comment]
古すぎるのでクローズする
