### ISSUE TITLE
IntOpt の訳

### ISSUE THREAD

**Issue by amotoki** [openstack-ja/openstack-manuals#55]
ch_ops_projects_users.xml.ja.po のレビューの中で指摘がありました。

IntOpt の訳として何がよいか
・整数オプション
・整数型
・整数値
・整数

表の中の項目でタイトル行には「(Type) Description」→「(型) 説明」と書かれています。

**Comment by amotoki** [comment]
タイトル行の「型」と一致しているので、吉山さん案の「整数型」にしてみました。
必要であればここで議論しましょう。

**Comment by ghost** [comment]
「整数型」でいいと思います。
Optに相当する語が抜け落ちますが、文脈から明らかなため、必ずしも明示的に訳しておく必要はないかなと思います。

**Comment by yosshy** [comment]
異論なさそうですので、クローズして良いと思います。

**Comment by amotoki** [comment]
ありがとうございます。意見が一致したようなのでクローズします。
