### ISSUE TITLE
in-band, out-of-band 

### ISSUE THREAD

**Issue by amotoki** [openstack-ja/openstack-manuals#56]
doc/src/docbkx/openstack-ops/src/ch_arch_network_design.xml:112 に
以下のような表現がある。

https://github.com/openstack-ja/openstack-manuals/pull/19 で
「アウトバンドという言葉があまり一般的ではない気がします。」とのコメントあり。

個人的には、in-band, out-of-band をインバンド、アウトバンドというのは通信としては一般的だと思っていますが、日本語での適切な表現が思いつかないので、アドバイスあればお願いします。意味としては、データ通信に使うメインの通信路を管理系と共用するのが in-band で、別に用意するのが out-of-band です。

```
msgid "out-of-band remote management"
msgstr "アウトバンドのリモート管理"

msgid "in-band remote management"
msgstr "インバンドのリモート管理"
```

**Comment by yosshy** [comment]
http://ejje.weblio.jp/ によると、「帯域内」「帯域外」とも訳せるようです。
ただ、インバンド、アウトバンドという表現もあるようで、気にしなくても良い気がしてきました。

**Comment by amotoki** [comment]
ありがとうございます。
今回の文脈では「帯域内」「帯域外」と訳すのは適切ではないと判断して使いませんでした。
同意頂けたので、クローズします。

他に out-of-band (OOB) を使う例としては、TCP の OOB 通知がありますが、これを訳すときには、かろうじて「帯域外」でも意味が通じるかなと思います。でも、「帯域外」と訳したことはないですね。
