### ISSUE TITLE
一部原文の更新に追いついていない

### ISSUE THREAD

**Issue by ghost** [openstack-ja/openstack-manuals#57]
Transifex の pot ファイルも更新されていませんが、原文が一部更新されています。
最新のリポジトリを使用すると、一部翻訳になります。
追いついていない更新量は少しのため、翻訳して追いつきませんか？

**Comment by amotoki** [comment]
はい。修正も反映されていますので、そうしたいと思っていましたが、
いったん翻訳をまとめる前に原文を更新すると混乱しそうなので、そうしていました。

Transifex の方の更新タイミングも現状不明なので、ソースを更新しにくいのが、
Transifex を使うデメリットだと思っています。あとは、翻訳する側のタイミングにあわせて
オリジナルをコントロールしたい場合もあるので、そのあたりも難しいところです。

**Comment by amotoki** [comment]
https://github.com/openstack-ja/operations-guide/pull/1 に更新のレビューを挙げました。よろしくお願いします。

operations-guide の git repository が分離されたので、同様に openstack-ja 側も fork repository を作り、
原文の更新を反映しています。上記の pull request は、その変更部分の翻訳更新に相当します。

**Comment by ghost** [comment]
遅くなりましたが、確認しました。

**Comment by amotoki** [comment]
8月時点でのキャッチアップは openstack-ja/operations-guide のレポジトリに反映しました。
https://github.com/openstack-ja/operations-guide/tree/ja-20130726
まだ、ウェブサイトの方は更新していません。

Transifex は更新されていませんが、現在手元で最新版へキャッチアップ中です。こちらは別途。
