### ISSUE TITLE
ダブルクォート囲みと「」囲みが統一されていない

### ISSUE THREAD

**Issue by ghost** [openstack-ja/openstack-manuals#58]
ダブルクォート囲みと「」囲みが統一されていない。
議論の結果、「」囲みに統一する方向で進んでいる。

〜〜
個別のブランチがマージされているので、以下の手順で修正する。
2つ方法があります。

個別のファイルを修正する方法
trans-ja-opsguide ブランチを checkout
chap/ 以下のファイルを修正する
./tool/chap-merge.sh を実行 (ja.po に変更が反映されます)
ja.po を修正する方法
trans-ja-opsguide ブランチを checkout
ja.po を修正する
./tool/chap-split.sh を実行 (chap/XXXX が更新されます)

**Comment by amotoki** [comment]
@katomo (加藤さん) かぎ括弧の件は途中まで進めたものがこちらにあるので、こちらで引き取りたいのですがどうでしょうか。

**Comment by ghost** [comment]
すみません、ちょうど私のほうで作業して、コミットしてしまいました。コミットのコメントに誤字も。。。
