### ISSUE TITLE
用語：controller node、compute node

### ISSUE THREAD

**Issue by yosshy** [openstack-ja/openstack-manuals#6]
controller node、compute node の訳を統一する。

現在、controller node、compute node の訳語には
- controller ノード／compute ノード
- コントローラノード／コンピュートノード
- 制御ノード／計算ノード

のそれぞれ３つが存在する。これをいずれかに統一する必要がある。

**Comment by amotoki** [comment]
統一すべきですね。個人的には「コントローラノード／コンピュートノード」です。次点は controller ノード／ compute ノードです。

**Comment by yosshy** [comment]
#opst12 で議論した結果、「コントローラノード／コンピュートノード」になりました。
