### ISSUE TITLE
link タグが付いている文章の翻訳が反映されない？

### ISSUE THREAD

**Issue by irixjp** [openstack-ja/openstack-manuals#7]
元の文章に link タグが含まれている文章が http://dream.daynight.jp/openstack/openstack-ops/content/ で英文のままになってしまっている気がします。
これってこういうものでしょうか？

**Comment by amotoki** [comment]
#4 の問題と同じです。 今、本家の docs ML で議論しています。 link タグの中に xlink:href や xlink:title のように xlink: がある場合と xlink ないの場合が、変換プログラムの中で混乱しているようです。

**Comment by irixjp** [comment]
はい、ありがとうございます！
