### ISSUE TITLE
用語集の用語の翻訳フォーマット

### ISSUE THREAD

**Issue by yosshy** [openstack-ja/openstack-manuals#9]
用語の翻訳を書く際に
- 翻訳語
- 翻訳語（元用語）
- 元用語
- 翻訳語＋本文に元用語
  など、いずれにするか決定する。

**Comment by yosshy** [comment]
翻訳語（元用語）は本文中のWebヘルプ版ポップアップの用語とマッチしないのでNG

**Comment by amotoki** [comment]
「翻訳語（元用語）」だと、Webヘルプ版のポップアップが出ないのでしょうか？
ポップアップが表示されるのであれば、情報量が多いのでよいように思います。

**Comment by amotoki** [comment]
結論はどれになったのでしょうか？
確認したいので、Reopen します。

**Comment by ghost** [comment]
申し訳ないです。ちょっと見たときに誤ってクローズしたようです。

Webヘルプ版のポップアップですが、次のように単純に文字列一致させています。

| ・用語定義箇所
|   &lt;glossentry&gt;&lt;glossterm&gt;用語&lt;/glossterm&gt;&lt;glossdef&gt;用語の説明&lt;/glossdef&gt;&lt;/glossentry&gt;
| ・本文参照箇所
|   ～～&lt;glossterm&gt;用語&lt;/glossterm&gt;～～

本文に&lt;glossterm&gt;用語&lt;/glossterm&gt;があると、&lt;glossentry&gt;の&lt;glossterm&gt;において、
用語と一致する文字列を検索し、見つかった glossdef の内容がポップアップ表示されます。
一致しなかった場合、ポップアップには何も表示されません。
そのため、各選択肢は次のようになると思います。

・翻訳語
　→ 本文と一致させやすい。元用語が不明になる。
・翻訳語（元用語）
　→ ポップアップ表示させるには、本文の&lt;glossterm&gt;を同じスタイルに修正する必要あり。
　　 または、ポップアップ表示をあきらめる。元用語がわかりやすい。
・元用語
　→ ポップアップ表示させるには、本文の&lt;glossterm&gt;を翻訳できない。
　　 または、ポップアップ表示をあきらめる。
・翻訳語＋本文に元用語
　→ ポップアップ表示をさせやすい。ポップアップ内に元用語が記載されているため参考になる。
　　 用語説明の先頭に元用語が表示されるスタイルのため、用語集として違和感がある可能性あり。

**Comment by ghost** [comment]
以前の打ち合わせでは、「翻訳語」を結論にしたと思っています。

**Comment by amotoki** [comment]
ありがとうございます。なるほど。
[TranslationGuideline](https://github.com/openstack-ja/openstack-manuals/wiki/TranslationGuideline) に記載しました。
クローズしましょう。
